todoapp/urls.py
from django.urls import path
from .views import *
app_name = "todoapp"
urlpatterns = [
    path("", SigninView.as_view(), name="signin"),
    path("signup/",SignupView.as_view(),name="signup"),
    path("signout/",SignoutView.as_view(),name="signout"),
    path("home/", HomeView.as_view(), name="home"),
    path('todolist/', TodoListView.as_view(), name='todolist'),
    path("todolist/<int:pk>/tododetail/",
         TodoDetailView.as_view(), name="todolistdetail"),
    path("todolistdetail/<int:pk>/step/",StepCreateView.as_view(),name="stepcreate"),
    path('todolist/create/',
     TodoCreateView.as_view(), name="todocreate"),
    path("ongoing/todolist/",OngoingView.as_view(),name="ongoingtodolist"),
    path("expired/todolist/",ExpireView.as_view(),name="expiretodolist"),


 
]

todoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls')),
 
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

todoapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class Todolist(TimeStamp):
    title = models.CharField(max_length=300)
    content = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    # author =models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(TimeStamp):
    todolist = models.ForeignKey(Todolist, on_delete=models.CASCADE)
    text=models.TextField()

todoapp/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User


class TodoForm(forms.ModelForm):
	class Meta:
		model=Comment
		fields=[ "text"]

class TodoCreateForm(forms.ModelForm):
	class Meta:
		model=Todolist
		fields="__all__"

class SigninForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your username...'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your password...'
    }))


class SignupForm(forms.Form):
	username=forms.CharField(widget=forms.TextInput())
	email=forms.CharField(widget=forms.EmailInput())
	password=forms.CharField(widget=forms.PasswordInput())
	confirm_password=forms.CharField(widget=forms.PasswordInput())

	def clean_username(self):
		uname = self.cleaned_data["username"]
		if User.objects.filter(username=uname).exists():
			raise forms.ValidationError("username already exists")
		return uname



	def clean_confirm_password(self):
		password = self.cleaned_data["password"]
		c_pword = self.cleaned_data["confirm_password"]
		if password != c_pword :
			raise forms.ValidationError("password didn't match ")
		return c_pword

todoapp/views.py
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views.generic import *
from .forms import *
from django.contrib.auth.models import User
from .models import *
from datetime import datetime, date, timedelta


# Create your views here.

today = date.today()

class SigninView(FormView):
    template_name = "signin.html"
    form_class = SigninForm
    success_url = reverse_lazy('todoapp:home')

    def form_valid(self, form):
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        # print(username,password,"welcome")

        user = authenticate(username=username, password=password)
        # print(user,"welcome")
        if user is not None:
            login(self.request, user)
        else:
            return render(self.request, "signin.html",
                          {"error": "invalid username or password",
                           "form": form

                           })

        return super().form_valid(form)

class SignupView(FormView):
    template_name="signup.html"
    form_class=SignupForm
    success_url="/"
    def form_valid(self,form):
        uname=form.cleaned_data["username"]
        email=form.cleaned_data["email"]
        pword=form.cleaned_data["password"]
        
        User.objects.create_user(uname,email,pword)

        return super().form_valid(form)

class SignoutView(View):
    def get (self,request):
        logout(request)
        return redirect(reverse_lazy('todoapp:signin'))

class BaseMixin(object):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["todoform"] = TodoForm


        return context
class HomeView(LoginRequiredMixin,BaseMixin,TemplateView):
    template_name = "home.html"
    def dispatch(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            pass
        else:
            return redirect("/signin")
        return super().dispatch(request,*args,**kwargs)


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['today'] = today
        context['todolist']=Todolist.objects.filter(end_date__gt=today).order_by('-start_date')
        context['exptodolist'] = Todolist.objects.filter(end_date__lt=today).order_by('-start_date')

        
      
        return context



class TodoListView(LoginRequiredMixin,ListView):
    template_name = "todolist.html"
    queryset = Todolist.objects.filter().order_by('-start_date')
    context_object_name = "todolist"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['today'] = today
        context['exptodolist'] = Todolist.objects.filter(end_date__lt=today)
        print(today)
        return context

class OngoingView(LoginRequiredMixin,ListView):
    template_name = "ongointodolist.html"
    queryset = Todolist.objects.filter().order_by('-start_date')
    context_object_name = "ongoingtodolist"


class ExpireView(LoginRequiredMixin,ListView):
    template_name = "expiretodolist.html"
    queryset = Todolist.objects.filter().order_by('-start_date')
    context_object_name = "todolist"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['today'] = today
        context['exptodolist'] = Todolist.objects.filter(end_date__lt=today)
        print(today)
        return context


class TodoDetailView(LoginRequiredMixin,BaseMixin,DetailView):
    template_name = "todolistdetail.html"
    model = Todolist
    context_object_name = "todoobject"

class StepCreateView(LoginRequiredMixin,BaseMixin,CreateView):
    template_name="todo.html"
    form_class=TodoForm
    success_url=reverse_lazy('todoapp:todolist')
    def form_valid (self,form):
        todolist_id=self.kwargs["pk"]
        todolist=Todolist.objects.get(id=todolist_id)
        form.instance.todolist=todolist
   

class TodoCreateView(LoginRequiredMixin,BaseMixin, CreateView):
    template_name = "todocreate.html"
    form_class = TodoCreateForm
    success_url = reverse_lazy('todoapp:home')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<style>
nav#nav1{ margin-top: 24px; }
nav#nav1 > a{ background:red; color:#000; padding:10px; text-decoration:none; border-radius:5px; font-family:"Arial White", Gadget, sans-serif; }
nav#nav1 > a:hover{ background: blue; }
nav#nav1 > a:active{ background: red; }
</style>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

	<title></title>
</head>
<body>
<script>
var bleep = new Audio();
bleep.src = "{% static 'media/bleep.mp3' %}";


</script>
</body>
</html>


  <br>
<div class="container-fluid">
{% if request.user.is_authenticated %}
      <li class="nav-item active">
      <p> Logged in as:<span class="text-danger">{{request.user}}</span> </p>
      </li>
{% endif %}
<a  class="btn btn-info" href="{% url 'todoapp:home' %}">Home</a>
<a  class="btn btn-info" href="{% url 'todoapp:todocreate' %}">Createnew task</a>
	<a  class="btn btn-info" href="{% url 'todoapp:todolist' %}">View all task</a>
	<a  class="btn btn-info" href="{% url 'todoapp:signout' %}">Signout</a>
<hr>
<p class="text-center">Your task list</p>
</div>







{% block content %}
{% endblock %}

templates/expiretodo.html
<div class="container">
<p class="text-center">Expire project lits..</p>
<div class="row">
{% for todo in exptodolist %}
	<aside class="col-sm-3">

{%  extends "base.html" %}
{% load static %}

	{% block content %}
<div class="card">

	<article class="card-group-item">
		<header class="card-header" ><b>
		<h6 class="title">{{todo.title}} </h6></b></header>
		<p style="text-align: center;">Steps</p>
		<hr>






		<div class="filter-content">
			<div class="list-group list-group-flush">
		{% for comment in todoobject.comment_set.all %}
			  <a href="#" class="list-group-item">{{comment.text}} <span class="float-right badge badge-light round">142</span> </a>
			{% empty %}
		<p>No Progress yet :(</p>
			{% endfor %}
			</div>  <!-- list-group .// -->
		</div>
		
	</article> <!-- card-group-item.// -->
	<article class="card-group-item">
		
		<!-- <h5>Start Date:{{todo.start_date}}</h5>
		<p>Expected end date:{{todo.end_date}}</p>
		<hr> -->
		<header class="card-header">
		<h6 class="title">Task Status</h6>
		<p><a href="{% url 'todoapp:todolistdetail' todo.id %}">View detail</a></p>


		</header>
		<div class="filter-content">
			
			<div class="card-body">
			
			
			
                 {% if todo.end_date < today %} 
				<label class="btn btn-danger">
				 
				  Expired
				</label>
				{% else %} 
				<label class="btn btn-info">
				  
				  Ongoing
				</label>
				
			{% endif %}
		</div>
		




	</article> <!-- card-group-item.// -->

</div> <!-- card.// -->



	</aside> <!-- col.// -->
{% endfor %}
</div> <!-- row.// -->
<a  class="btn btn-info text-center" href="{% url 'todoapp:expiretodolist' %}" >View all Expire task</a>
</div>

{% endblock %} 

templates/home.html
{%  extends "base.html" %}
{% load static %}

	{% block content %}
	
<div class="container">
<p class="text-center">Your on going project lits..</p>
<div class="row">
{% for todo in todolist|slice:"4"  %}
	<aside class="col-sm-3">


<div class="card">

	<article class="card-group-item">
		<header class="card-header" ><b>
		<h6 class="title">{{todo.title}} </h6></b></header>
		<p style="text-align: center;">Steps</p>
		<hr>



<!-- 		{% for comment in todoobject.comment_set.all %}
		<li>  {{comment.text}} </li>
		
		{% empty %}
		<p>No Progress yet :(</p>
		{% endfor %} -->




		<div class="filter-content">
			<div class="list-group list-group-flush">
		{% for comment in todo.comment_set.all %}
			  <p class="list-group-item">{{comment.text}} on {{comment.created_at}}</p>
			{% empty %}
		<p>No Progress yet :(</p>
			{% endfor %}
			</div>  <!-- list-group .// -->
		</div>
		
	</article> <!-- card-group-item.// -->
	<article class="card-group-item">
		
		<!-- <h5>Start Date:{{todo.start_date}}</h5>
		<p>Expected end date:{{todo.end_date}}</p>
		<hr> -->

		<header class="card-header">
		<h6 class="title">Task Status</h6>
	
	
 {% if todo.end_date < today %} 
				<label class="btn btn-danger" >
				 
				  Expired
				</label>

				{% else %} 
				<label class="btn btn-info">
				  
				  Ongoing
				</label>

		</header>
		<div class="filter-content">
			
			<div class="card-body">
			
			
			
                
			
					<p><a href="{% url 'todoapp:todolistdetail' todo.id %}">View detail</a></p>
			{% endif %}
		</div>
		




	</article> <!-- card-group-item.// -->

</div> <!-- card.// -->



	</aside> <!-- col.// -->
{% endfor %}
</div> <!-- row.// -->
</div>
<hr>
<a  class="btn btn-info text-center" href="{% url 'todoapp:ongoingtodolist' %}" >View all ongoing task</a>
 <div class="container">
<p class="text-center">Expire project lits..</p>
<div class="row">
{% for todo in exptodolist %}
	<aside class="col-sm-3">


<div class="card">

	<article class="card-group-item">
		<header class="card-header" ><b>
		<h6 class="title">{{todo.title}} </h6></b></header>
		<p style="text-align: center;">Steps</p>
		<hr>






		<div class="filter-content">
			<div class="list-group list-group-flush">
		{% for comment in todoobject.comment_set.all|slice:"4" %}
			  <a href="#" class="list-group-item">{{comment.text}} <span class="float-right badge badge-light round">142</span> </a>
			{% empty %}
		<p>No Progress yet :(</p>
			{% endfor %}
			</div>  <!-- list-group .// -->
		</div>
		
	</article> <!-- card-group-item.// -->
	<article class="card-group-item">
		
		<!-- <h5>Start Date:{{todo.start_date}}</h5>
		<p>Expected end date:{{todo.end_date}}</p>
		<hr> -->
		<header class="card-header">
		<h6 class="title">Task Status</h6>
		
                 {% if todo.end_date < today %} 
					<nav id="nav1">
    <a href="#" onmousedown="bleep.play()">Expire</a>
    </nav>
				{% else %} 
				<label class="btn btn-info">
				  
				  Ongoing
				</label>
				
			{% endif %}


		</header>
		<div class="filter-content">
			
			<div class="card-body">
			
			
			
		<p><a href="{% url 'todoapp:todolistdetail' todo.id %}">View detail</a></p>
		</div>
		




	</article> <!-- card-group-item.// -->

</div> <!-- card.// -->



	</aside> <!-- col.// -->
{% endfor %}
</div> <!-- row.// -->
<a  class="btn btn-info text-center" href="{% url 'todoapp:expiretodolist' %}" >View all Expire task</a>
</div>

	{% endblock %} 

templates/signin.html
{% load static %}

{% block content %}

           
                <form method="post" action="{% url 'todoapp:signin' %}" style="text-align: center;">
                     {% if error %}
    <li class="text-danger">{{error}}</li>
    {% endif %}
                    {% csrf_token %}

                    {{form.as_p}}
                    
                    
                    <button type="submit" class="btn btn-primary ">Login</button>
                    <button><a href="{% url 'todoapp:signup' %}"> Register here</button></a>
                </form>
{% endblock %} 

templates/signup.html
	{% block content %}
	
	<h4>signup</h4>
	<form method="POST" action="">
		{% csrf_token %}
		{{form.as_p}}
<button>Signup</button>
	</form>



	{% endblock %}

templates/todocreate.html
{% extends 'base.html' %}

{% block content %}
<!-- main-heading -->
            <!-- <h2 class="main-title-w3layouts mb-2 text-center">Service Form</h2> -->
            <!--// main-heading -->

            <!-- Forms content -->
            <section class="forms-section">

              
                
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Add new project</h4>
                    <form action="{% url 'todoapp:todocreate'%}" method="POST" enctype="multipart/form-data">
                    	{% csrf_token %}
                    	{{form.as_p}}
                   
                        
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </div>
               
             
            </section>
{% endblock %}

templates/todolist.html
{%  extends "base.html" %}
{% load static %}


	{% block content %}

<!--   <a  class="btn btn-info" href="{% url 'todoapp:todocreate' %}">Createnew task</a>
<h3>My to do list</h3>
{% for todo in todolist %}
<li>todo name:{{todo.title}}{% if todo.end_date < today %} (expired) {% endif %}</li>
<p>start date:{{todo.start_date}}</p>
<p>Goal to be achieve untill:{{todo.end_date}}</p>
<a href="{% url 'todoapp:todolistdetail' todo.id %}">View detail</a>
                            
  {% endfor %} -->
<!-- 
<h3>Expired Todo list</h3>
{% for todo in exptodolist %}
<li>todo name:{{todo.title}}</li>
<p>start date:{{todo.start_date}}</p>
<p>Goal to be achieve untill:{{todo.end_date}}</p>
<a href="{% url 'todoapp:todolistdetail' todo.id %}">View detail</a>
                            
  {% endfor %} -->






<div class="container">
<div class="row">
{% for todo in todolist %}
	<aside class="col-sm-4">


<div class="card">

	<article class="card-group-item">
		<header class="card-header" ><b>
		<h6 class="title">{{todo.title}}{% if todo.end_date < today %} (expired) {% endif %} </h6></b></header>
		<p style="text-align: center;">Steps</p>
		<hr>



	<!-- 	{% for comment in todoobject.comment_set.all %}
		<li>  {{comment.text}} on {{comment.date|timesince}} ago</li>
		
		{% empty %}
		<p>No Progress yet :(</p>
		{% endfor %} -->




		<div class="filter-content">
			<div class="list-group list-group-flush">
		{% for comment in todoobject.comment_set.all %}
			  <a href="#" class="list-group-item">{{comment.text}} <span class="float-right badge badge-light round">142</span> </a>
			{% empty %}
		<p>No Progress yet :(</p>
			{% endfor %}
			</div>  <!-- list-group .// -->
		</div>
		
	</article> <!-- card-group-item.// -->
	<article class="card-group-item">
		
		<!-- <h5>Start Date:{{todo.start_date}}</h5>
		<p>Expected end date:{{todo.end_date}}</p>
		<hr> -->
		<header class="card-header">
		<h6 class="title">Task Status</h6>
		<p><a href="{% url 'todoapp:todolistdetail' todo.id %}">View detail</a></p>


		</header>
		<div class="filter-content">
			
			<div class="card-body">
			
			
			
                 {% if todo.end_date < today %} 
				<label class="btn btn-danger">
				 
				  Expired
				</label>
				{% else %} 
				<label class="btn btn-info">
				  
				  Ongoing
				</label>
				
			{% endif %}
		</div>
		




	</article> <!-- card-group-item.// -->

</div> <!-- card.// -->



	</aside> <!-- col.// -->
{% endfor %}
</div> <!-- row.// -->

</div>
	{% endblock %} 

templates/todolistdetail.html
{%  extends "base.html" %}
{% load static %}


	{% block content %}


<h3>My to do list</h3>

<li>todo name:{{todoobject.title}}</li>
<li>start date:{{todoobject.start_date}}</li>
<li>Goal to be achieve untill:{{todoobject.end_date}}</li>

                          
  

		<h4>Progress</h4>

		{% for comment in todoobject.comment_set.all %}
		<li>  {{comment.text}} on {{comment.date|timesince}} ago</li>
		
		{% empty %}
		<p>No Progress yet :(</p>
		{% endfor %}

		<h4>Add your progress report here</h4>

		<form method="POST" action="{% url 'todoapp:stepcreate' todoobject.pk %}">
			{% csrf_token %}
			{{todoform.as_p}}
			<button class="btn btn-success">Add report</button>

		</form>
	{% endblock %} 